development:
  adapter: postgresql
  encoding: utf8
  database: rtwood_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: rtwood_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: postgres
